ALTER TABLE users
  ADD COLUMN IF NOT EXISTS ui_locale TEXT NOT NULL DEFAULT 'en',
  ADD COLUMN IF NOT EXISTS ui_theme TEXT NOT NULL DEFAULT 'light';

ALTER TABLE sessions
  ADD COLUMN IF NOT EXISTS session_language TEXT NOT NULL DEFAULT 'en';
